import type { Metadata } from "next";
import { Livvic } from "next/font/google";
import "./globals.css";
import { MenuProvider } from "@/lib/context/menu-context";

const livvic = Livvic({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MenuProvider>
      <html lang="en">
        <body
          className={`${livvic.className} body-font bg-primary-green text-white`}
        >
          {children}
        </body>
      </html>
    </MenuProvider>
  );
}
